### ISSUE TITLE
Unable to decode Android APK when running AppVet on macOS

### ISSUE THREAD

**Issue by mediabounds** [AppVet/appvet#14]
When I try to review an APK in AppVet running on macOS, it fails.
<img width="1228" alt="screen shot 2017-02-07 at 10 09 41 am" src="https://cloud.githubusercontent.com/assets/480718/22699679/c690e84a-ed1d-11e6-8978-b463f407ad86.png">

In reviewing the source code, it seems like the path to `apktool` is likely not getting set correctly on macOS:
https://github.com/AppVet/appvet/blob/master/src/gov/nist/appvet/servlet/preprocessor/AndroidMetadata.java#L226

Neither one of these conditions will evaluate to `true`. macOS can probably be treated like a Linux/Unix environment so that `APKTOOL_LINUX_COMMAND` is appended to `apktoolCommand`.

**Comment by AppVet** [comment]
Yes, AppVet has not yet been tested on MacOS, unfortunately. I will add MacOS as a condition above and treat like Linux/Unix and will do the release later today or tomorrow. Thanks!

**Comment by mediabounds** [comment]
Thanks! I scanned the source code and this was the only OS-specific code path that stood out as a problem. I'll test it out when a new release is available.

**Comment by AppVet** [comment]
I have added a new release that adds the Mac OS condition, but I have no way of testing it. Can you run it and let me know if it works? Thanks!

https://github.com/AppVet/appvet/releases/tag/v2.4.10

**Comment by mediabounds** [comment]
That appears to have done the trick! App Metadata is now able to be read. Thanks again!
