### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by yapple** [AppVet/appvet#2]
You can add a module to support reverse proxy

**Comment by aglynn** [comment]
AppVet works well behind a reverse proxy currently. If you are having problems with getting it to work behind a reverse proxy, please past your reverse proxy configurations here as well as further details on how you have AppVet and the reverse proxy set up.

**Comment by yapple** [comment]
This is my nginx server configurations.
 server{
       listen  80;
       server_name     appvet.99gm.com;
       location /appvet/{
               proxy_pass http://localhost:8080/appvet/;
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header Host $host;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header REMOTE-HOST $remote_addr;
       }
        location /appvet_images/{
                proxy_pass http://localhost:8080/appvet_images/;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header REMOTE-HOST $remote_addr;
        }
}
A: http://appvet.99gm.com(reverse proxy)
B: http://99gm.com:8080/appvet
A can normally access, B can not.You can try it.

I think the problem is in (greet Servlet)'s request.
`gov.nist.appvet.gwt.server.GWTServiceImpl
 String clientIpAddress = request.getRemoteAddr();
`
Can you hear me ?

**Comment by yapple** [comment]
This is my nginx server configurations.
server{
listen 80;
server_name appvet.99gm.com;
location /appvet/{
proxy_pass http://localhost:8080/appvet/;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header REMOTE-HOST $remote_addr;
}
location /appvet_images/{
proxy_pass http://localhost:8080/appvet_images/;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header REMOTE-HOST $remote_addr;
}
}
A: http://appvet.99gm.com (reverse proxy)
B: http://99gm.com:8080/appvet
A can normally access, B can not.You can try it.

I think the problem is in (greet Servlet)'s request.
`gov.nist.appvet.gwt.server.GWTServiceImpl

String clientIpAddress = request.getRemoteAddr();
`
Can you hear me ?

**Comment by aglynn** [comment]
I wasn't able to log into your service. I am thinking that the problem might not be the reverse proxy. Are you sure that your Host element is configured correctly. I would imagine it would look like this below. Is this what yours currently looks like?


<Host>
		<Hostname>http://appvet.99gm.com</Hostname>
		<SSL>false</SSL>
		<Port>80</Port>
	</Host>

**Comment by yapple** [comment]
Sorry, you can use http://www.99gm.com:8080/appvet to login.

**Comment by aglynn** [comment]
I logged in and saw that your custom tool provided a "LOW" rating for the app. Great job creating a custom tool! I don't know exactly why your reverse proxy isn't working but I know that it does work just fine with a reverse proxy.

**Comment by yapple** [comment]
Maybe the reason for the configuration ! I will try to resolve it . 
My custom tool is too easy , just a framework . And I will enrich it .

**Comment by aglynn** [comment]
Sounds great. Keep me updated. I think the biggest challenge to getting AppVet more adopted is that there are not more AppVet tools that are available for people to run. I'd love to see what you create if you are cool with that.

I will close this ticket, but you can reopen later or open a new ticket you have another question.
